### ISSUE TITLE
Possible diagnosis of GET HTTP failure

### ISSUE THREAD

**Issue by austinscreations** [SuperHouse/OXRS-SHA-StateMonitor-ESP32-FW#24] opened 2022-02-13 01:31 UTC
try to diagnose issue with HTTP GET for config

my first thought would be to have jon drop down a version or a few to try and see if it starts working again...

**Comment by Cheaternl** [comment] 2022-02-14 14:02
If this happened during the live stream (which I have been watching), the steps to reproduce are:
1. Set the MQTT broker address and save it. (most important in this is to trigger the 'Save')
2. Now, config page doesn't work anymore.

Steps to have a working situation (workaround?) after setting the MQTT broker address.
1. Set the MQTT broker address and save it. (most important in this is to trigger the 'Save')
2. Restart the device (via the admin page)
2. Now, config page does work

Seems that setting the MQTT broker address / save action, breaks something.

**Comment by austinscreations** [comment] 2022-02-14 15:03
so far however jon's the only one who has run into the issue, quiet a few people have been testing the firmware and haven't had issue accessing any of the HTTP pages required for the webUI to work and having a single HTTP GET failure is rather odd

**Comment by sumnerboy12** [comment] 2022-02-14 20:11
@Cheaternl I just tested your steps on a Rack32 I have here. I did a factory reset, configured the MQTT settings and hit `Submit`, then loaded the config page - no problems, everything worked fine. 

I am stumped as to what was happening with Jon's.

**Comment by jonoxer** [comment] 2022-02-14 20:20
Without any specific evidence for it, my thoughts keep coming back to my network being the problem. I can't even think of a good theory about how that could happen though. On the livestream I had 2 different Rack32s both running the downloaded 3.9.1 binary, and they did the same thing. One is a v1.0 board assembled many months ago, and the other is a v1.1 board assembled last week. Even the WROOM32 modules on them should be from different batches.

The livestream wasn't a great time to dig into it deeper so I'll try a few things when I get a chance:
 1. Test the specific steps required to reproduce.
 2. Test on an isolated network with just 2 devices, with the DHCP server running on the other device.
 3. Use Wireshark to see differences between successful and unsuccessful calls to that endpoint.

If there are other specific tests I should do, let me know.

**Comment by sumnerboy12** [comment] 2022-02-14 20:29
One thing to note, if you call `/api/config` on a fresh/factory reset device, there will be no config on SPIFFS and the device will return 204. I don't think this should cause an `ERR_CONNECTION_REFUSED` in your browser but it might be related?

This is slightly different for `/api/mqtt` and `/api/adopt` which always return something, even if there is no MQTT broker configured.

**Comment by sumnerboy12** [comment] 2022-03-30 20:09
@jonoxer have you ever seen this behaviour again? If not I think we can probably close this issue and assume it was some kind of network related issue.

**Comment by sumnerboy12** [comment] 2022-08-17 10:24
Closing this due to inactivity and no further reports of any problems.

**Closed as not planned by sumnerboy12** 2022-08-17 10:24 UTC
